"""
Python SDK for OpenFGA

API version: 1.x
Website: https://openfga.dev
Documentation: https://openfga.dev/docs
Support: https://openfga.dev/community
License: [Apache-2.0](https://github.com/openfga/python-sdk/blob/main/LICENSE)

NOTE: This file was auto generated by OpenAPI Generator (https://openapi-generator.tech). DO NOT EDIT.
"""

import unittest
from unittest.mock import Mock

from openfga_sdk.configuration import Configuration
from openfga_sdk.models.write_request_deletes import WriteRequestDeletes


class TestWriteRequestDeletes(unittest.TestCase):
    """Test for WriteRequestDeletes"""

    def test_write_request_deletes_init_defaults(self):
        """Test WriteRequestDeletes initialization with defaults"""
        tuple_keys = [Mock()]
        deletes = WriteRequestDeletes(tuple_keys=tuple_keys)
        self.assertEqual(deletes.tuple_keys, tuple_keys)
        self.assertEqual(deletes.on_missing, "error")

    def test_write_request_deletes_init_with_on_missing_error(self):
        """Test WriteRequestDeletes initialization with on_missing='error'"""
        tuple_keys = [Mock()]
        deletes = WriteRequestDeletes(tuple_keys=tuple_keys, on_missing="error")
        self.assertEqual(deletes.tuple_keys, tuple_keys)
        self.assertEqual(deletes.on_missing, "error")

    def test_write_request_deletes_init_with_on_missing_ignore(self):
        """Test WriteRequestDeletes initialization with on_missing='ignore'"""
        tuple_keys = [Mock()]
        deletes = WriteRequestDeletes(tuple_keys=tuple_keys, on_missing="ignore")
        self.assertEqual(deletes.tuple_keys, tuple_keys)
        self.assertEqual(deletes.on_missing, "ignore")

    def test_write_request_deletes_init_with_none_on_missing(self):
        """Test WriteRequestDeletes initialization with on_missing=None"""
        tuple_keys = [Mock()]
        deletes = WriteRequestDeletes(tuple_keys=tuple_keys, on_missing=None)
        self.assertEqual(deletes.tuple_keys, tuple_keys)
        self.assertIsNone(deletes.on_missing)

    def test_write_request_deletes_init_with_local_vars_configuration(self):
        """Test WriteRequestDeletes initialization with custom configuration"""
        config = Configuration()
        tuple_keys = [Mock()]
        deletes = WriteRequestDeletes(
            tuple_keys=tuple_keys, local_vars_configuration=config
        )
        self.assertEqual(deletes.tuple_keys, tuple_keys)
        self.assertEqual(deletes.local_vars_configuration, config)

    def test_tuple_keys_setter(self):
        """Test tuple_keys setter"""
        tuple_keys = [Mock()]
        deletes = WriteRequestDeletes(tuple_keys=tuple_keys)
        new_tuple_keys = [Mock(), Mock()]
        deletes.tuple_keys = new_tuple_keys
        self.assertEqual(deletes.tuple_keys, new_tuple_keys)

    def test_tuple_keys_setter_raises_error_for_none(self):
        """Test tuple_keys setter raises ValueError for None"""
        tuple_keys = [Mock()]
        deletes = WriteRequestDeletes(tuple_keys=tuple_keys)
        with self.assertRaises(ValueError) as context:
            deletes.tuple_keys = None
        self.assertIn("Invalid value for `tuple_keys`", str(context.exception))

    def test_on_missing_setter_error(self):
        """Test on_missing setter with 'error'"""
        tuple_keys = [Mock()]
        deletes = WriteRequestDeletes(tuple_keys=tuple_keys)
        deletes.on_missing = "error"
        self.assertEqual(deletes.on_missing, "error")

    def test_on_missing_setter_ignore(self):
        """Test on_missing setter with 'ignore'"""
        tuple_keys = [Mock()]
        deletes = WriteRequestDeletes(tuple_keys=tuple_keys)
        deletes.on_missing = "ignore"
        self.assertEqual(deletes.on_missing, "ignore")

    def test_on_missing_setter_raises_error_for_invalid_value(self):
        """Test on_missing setter raises ValueError for invalid value"""
        tuple_keys = [Mock()]
        deletes = WriteRequestDeletes(tuple_keys=tuple_keys)
        with self.assertRaises(ValueError) as context:
            deletes.on_missing = "invalid"
        self.assertIn("Invalid value for `on_missing`", str(context.exception))

    def test_to_dict_basic(self):
        """Test to_dict method with basic data"""
        tuple_keys = [Mock()]
        tuple_keys[0].to_dict = Mock(return_value={"key": "value"})
        deletes = WriteRequestDeletes(tuple_keys=tuple_keys, on_missing="error")
        result = deletes.to_dict()
        self.assertIn("tuple_keys", result)
        self.assertIn("on_missing", result)
        self.assertEqual(result["on_missing"], "error")

    def test_to_dict_serialize(self):
        """Test to_dict method with serialize=True"""
        tuple_keys = [Mock()]
        tuple_keys[0].to_dict = Mock(return_value={"key": "value"})
        deletes = WriteRequestDeletes(tuple_keys=tuple_keys, on_missing="ignore")
        result = deletes.to_dict(serialize=True)
        self.assertIn("tuple_keys", result)
        self.assertIn("on_missing", result)
        self.assertEqual(result["on_missing"], "ignore")

    def test_to_str(self):
        """Test to_str method"""
        tuple_keys = [Mock()]
        tuple_keys[0].to_dict = Mock(return_value={"key": "value"})
        deletes = WriteRequestDeletes(tuple_keys=tuple_keys)
        result = deletes.to_str()
        self.assertIsInstance(result, str)

    def test_repr(self):
        """Test __repr__ method"""
        tuple_keys = [Mock()]
        tuple_keys[0].to_dict = Mock(return_value={"key": "value"})
        deletes = WriteRequestDeletes(tuple_keys=tuple_keys)
        result = repr(deletes)
        self.assertIsInstance(result, str)

    def test_eq_same_object(self):
        """Test __eq__ with same object"""
        tuple_keys = [Mock()]
        tuple_keys[0].to_dict = Mock(return_value={"key": "value"})
        deletes = WriteRequestDeletes(tuple_keys=tuple_keys, on_missing="error")
        self.assertEqual(deletes, deletes)

    def test_eq_equal_objects(self):
        """Test __eq__ with equal objects"""
        tuple_keys1 = [Mock()]
        tuple_keys1[0].to_dict = Mock(return_value={"key": "value"})
        deletes1 = WriteRequestDeletes(tuple_keys=tuple_keys1, on_missing="error")

        tuple_keys2 = [Mock()]
        tuple_keys2[0].to_dict = Mock(return_value={"key": "value"})
        deletes2 = WriteRequestDeletes(tuple_keys=tuple_keys2, on_missing="error")

        self.assertEqual(deletes1, deletes2)

    def test_eq_different_objects(self):
        """Test __eq__ with different objects"""
        tuple_keys1 = [Mock()]
        tuple_keys1[0].to_dict = Mock(return_value={"key": "value1"})
        deletes1 = WriteRequestDeletes(tuple_keys=tuple_keys1, on_missing="error")

        tuple_keys2 = [Mock()]
        tuple_keys2[0].to_dict = Mock(return_value={"key": "value2"})
        deletes2 = WriteRequestDeletes(tuple_keys=tuple_keys2, on_missing="ignore")

        self.assertNotEqual(deletes1, deletes2)

    def test_eq_with_non_write_request_deletes(self):
        """Test __eq__ with non-WriteRequestDeletes object"""
        tuple_keys = [Mock()]
        tuple_keys[0].to_dict = Mock(return_value={"key": "value"})
        deletes = WriteRequestDeletes(tuple_keys=tuple_keys)
        self.assertNotEqual(deletes, "not a WriteRequestDeletes")

    def test_ne_different_objects(self):
        """Test __ne__ with different objects"""
        tuple_keys1 = [Mock()]
        tuple_keys1[0].to_dict = Mock(return_value={"key": "value1"})
        deletes1 = WriteRequestDeletes(tuple_keys=tuple_keys1, on_missing="error")

        tuple_keys2 = [Mock()]
        tuple_keys2[0].to_dict = Mock(return_value={"key": "value2"})
        deletes2 = WriteRequestDeletes(tuple_keys=tuple_keys2, on_missing="ignore")

        self.assertTrue(deletes1 != deletes2)

    def test_ne_with_non_write_request_deletes(self):
        """Test __ne__ with non-WriteRequestDeletes object"""
        tuple_keys = [Mock()]
        tuple_keys[0].to_dict = Mock(return_value={"key": "value"})
        deletes = WriteRequestDeletes(tuple_keys=tuple_keys)
        self.assertTrue(deletes != "not a WriteRequestDeletes")

    def test_openapi_types(self):
        """Test openapi_types class attribute"""
        self.assertIn("tuple_keys", WriteRequestDeletes.openapi_types)
        self.assertIn("on_missing", WriteRequestDeletes.openapi_types)

    def test_attribute_map(self):
        """Test attribute_map class attribute"""
        self.assertIn("tuple_keys", WriteRequestDeletes.attribute_map)
        self.assertIn("on_missing", WriteRequestDeletes.attribute_map)
