"""
Python SDK for OpenFGA

API version: 1.x
Website: https://openfga.dev
Documentation: https://openfga.dev/docs
Support: https://openfga.dev/community
License: [Apache-2.0](https://github.com/openfga/python-sdk/blob/main/LICENSE)

NOTE: This file was auto generated by OpenAPI Generator (https://openapi-generator.tech). DO NOT EDIT.
"""

import unittest
from unittest.mock import Mock

from openfga_sdk.configuration import Configuration
from openfga_sdk.models.write_request_writes import WriteRequestWrites


class TestWriteRequestWrites(unittest.TestCase):
    """Test for WriteRequestWrites"""

    def test_write_request_writes_init_defaults(self):
        """Test WriteRequestWrites initialization with defaults"""
        tuple_keys = [Mock()]
        writes = WriteRequestWrites(tuple_keys=tuple_keys)
        self.assertEqual(writes.tuple_keys, tuple_keys)
        self.assertEqual(writes.on_duplicate, "error")

    def test_write_request_writes_init_with_on_duplicate_error(self):
        """Test WriteRequestWrites initialization with on_duplicate='error'"""
        tuple_keys = [Mock()]
        writes = WriteRequestWrites(tuple_keys=tuple_keys, on_duplicate="error")
        self.assertEqual(writes.tuple_keys, tuple_keys)
        self.assertEqual(writes.on_duplicate, "error")

    def test_write_request_writes_init_with_on_duplicate_ignore(self):
        """Test WriteRequestWrites initialization with on_duplicate='ignore'"""
        tuple_keys = [Mock()]
        writes = WriteRequestWrites(tuple_keys=tuple_keys, on_duplicate="ignore")
        self.assertEqual(writes.tuple_keys, tuple_keys)
        self.assertEqual(writes.on_duplicate, "ignore")

    def test_write_request_writes_init_with_none_on_duplicate(self):
        """Test WriteRequestWrites initialization with on_duplicate=None"""
        tuple_keys = [Mock()]
        writes = WriteRequestWrites(tuple_keys=tuple_keys, on_duplicate=None)
        self.assertEqual(writes.tuple_keys, tuple_keys)
        self.assertIsNone(writes.on_duplicate)

    def test_write_request_writes_init_with_local_vars_configuration(self):
        """Test WriteRequestWrites initialization with custom configuration"""
        config = Configuration()
        tuple_keys = [Mock()]
        writes = WriteRequestWrites(
            tuple_keys=tuple_keys, local_vars_configuration=config
        )
        self.assertEqual(writes.tuple_keys, tuple_keys)
        self.assertEqual(writes.local_vars_configuration, config)

    def test_tuple_keys_setter(self):
        """Test tuple_keys setter"""
        tuple_keys = [Mock()]
        writes = WriteRequestWrites(tuple_keys=tuple_keys)
        new_tuple_keys = [Mock(), Mock()]
        writes.tuple_keys = new_tuple_keys
        self.assertEqual(writes.tuple_keys, new_tuple_keys)

    def test_tuple_keys_setter_raises_error_for_none(self):
        """Test tuple_keys setter raises ValueError for None"""
        tuple_keys = [Mock()]
        writes = WriteRequestWrites(tuple_keys=tuple_keys)
        with self.assertRaises(ValueError) as context:
            writes.tuple_keys = None
        self.assertIn("Invalid value for `tuple_keys`", str(context.exception))

    def test_on_duplicate_setter_error(self):
        """Test on_duplicate setter with 'error'"""
        tuple_keys = [Mock()]
        writes = WriteRequestWrites(tuple_keys=tuple_keys)
        writes.on_duplicate = "error"
        self.assertEqual(writes.on_duplicate, "error")

    def test_on_duplicate_setter_ignore(self):
        """Test on_duplicate setter with 'ignore'"""
        tuple_keys = [Mock()]
        writes = WriteRequestWrites(tuple_keys=tuple_keys)
        writes.on_duplicate = "ignore"
        self.assertEqual(writes.on_duplicate, "ignore")

    def test_on_duplicate_setter_raises_error_for_invalid_value(self):
        """Test on_duplicate setter raises ValueError for invalid value"""
        tuple_keys = [Mock()]
        writes = WriteRequestWrites(tuple_keys=tuple_keys)
        with self.assertRaises(ValueError) as context:
            writes.on_duplicate = "invalid"
        self.assertIn("Invalid value for `on_duplicate`", str(context.exception))

    def test_to_dict_basic(self):
        """Test to_dict method with basic data"""
        tuple_keys = [Mock()]
        tuple_keys[0].to_dict = Mock(return_value={"key": "value"})
        writes = WriteRequestWrites(tuple_keys=tuple_keys, on_duplicate="error")
        result = writes.to_dict()
        self.assertIn("tuple_keys", result)
        self.assertIn("on_duplicate", result)
        self.assertEqual(result["on_duplicate"], "error")

    def test_to_dict_serialize(self):
        """Test to_dict method with serialize=True"""
        tuple_keys = [Mock()]
        tuple_keys[0].to_dict = Mock(return_value={"key": "value"})
        writes = WriteRequestWrites(tuple_keys=tuple_keys, on_duplicate="ignore")
        result = writes.to_dict(serialize=True)
        self.assertIn("tuple_keys", result)
        self.assertIn("on_duplicate", result)
        self.assertEqual(result["on_duplicate"], "ignore")

    def test_to_str(self):
        """Test to_str method"""
        tuple_keys = [Mock()]
        tuple_keys[0].to_dict = Mock(return_value={"key": "value"})
        writes = WriteRequestWrites(tuple_keys=tuple_keys)
        result = writes.to_str()
        self.assertIsInstance(result, str)

    def test_repr(self):
        """Test __repr__ method"""
        tuple_keys = [Mock()]
        tuple_keys[0].to_dict = Mock(return_value={"key": "value"})
        writes = WriteRequestWrites(tuple_keys=tuple_keys)
        result = repr(writes)
        self.assertIsInstance(result, str)

    def test_eq_same_object(self):
        """Test __eq__ with same object"""
        tuple_keys = [Mock()]
        tuple_keys[0].to_dict = Mock(return_value={"key": "value"})
        writes = WriteRequestWrites(tuple_keys=tuple_keys, on_duplicate="error")
        self.assertEqual(writes, writes)

    def test_eq_equal_objects(self):
        """Test __eq__ with equal objects"""
        tuple_keys1 = [Mock()]
        tuple_keys1[0].to_dict = Mock(return_value={"key": "value"})
        writes1 = WriteRequestWrites(tuple_keys=tuple_keys1, on_duplicate="error")

        tuple_keys2 = [Mock()]
        tuple_keys2[0].to_dict = Mock(return_value={"key": "value"})
        writes2 = WriteRequestWrites(tuple_keys=tuple_keys2, on_duplicate="error")

        self.assertEqual(writes1, writes2)

    def test_eq_different_objects(self):
        """Test __eq__ with different objects"""
        tuple_keys1 = [Mock()]
        tuple_keys1[0].to_dict = Mock(return_value={"key": "value1"})
        writes1 = WriteRequestWrites(tuple_keys=tuple_keys1, on_duplicate="error")

        tuple_keys2 = [Mock()]
        tuple_keys2[0].to_dict = Mock(return_value={"key": "value2"})
        writes2 = WriteRequestWrites(tuple_keys=tuple_keys2, on_duplicate="ignore")

        self.assertNotEqual(writes1, writes2)

    def test_eq_with_non_write_request_writes(self):
        """Test __eq__ with non-WriteRequestWrites object"""
        tuple_keys = [Mock()]
        tuple_keys[0].to_dict = Mock(return_value={"key": "value"})
        writes = WriteRequestWrites(tuple_keys=tuple_keys)
        self.assertNotEqual(writes, "not a WriteRequestWrites")

    def test_ne_different_objects(self):
        """Test __ne__ with different objects"""
        tuple_keys1 = [Mock()]
        tuple_keys1[0].to_dict = Mock(return_value={"key": "value1"})
        writes1 = WriteRequestWrites(tuple_keys=tuple_keys1, on_duplicate="error")

        tuple_keys2 = [Mock()]
        tuple_keys2[0].to_dict = Mock(return_value={"key": "value2"})
        writes2 = WriteRequestWrites(tuple_keys=tuple_keys2, on_duplicate="ignore")

        self.assertTrue(writes1 != writes2)

    def test_ne_with_non_write_request_writes(self):
        """Test __ne__ with non-WriteRequestWrites object"""
        tuple_keys = [Mock()]
        tuple_keys[0].to_dict = Mock(return_value={"key": "value"})
        writes = WriteRequestWrites(tuple_keys=tuple_keys)
        self.assertTrue(writes != "not a WriteRequestWrites")

    def test_openapi_types(self):
        """Test openapi_types class attribute"""
        self.assertIn("tuple_keys", WriteRequestWrites.openapi_types)
        self.assertIn("on_duplicate", WriteRequestWrites.openapi_types)

    def test_attribute_map(self):
        """Test attribute_map class attribute"""
        self.assertIn("tuple_keys", WriteRequestWrites.attribute_map)
        self.assertIn("on_duplicate", WriteRequestWrites.attribute_map)
