"""
Python SDK for OpenFGA

API version: 1.x
Website: https://openfga.dev
Documentation: https://openfga.dev/docs
Support: https://openfga.dev/community
License: [Apache-2.0](https://github.com/openfga/python-sdk/blob/main/LICENSE)

NOTE: This file was auto generated by OpenAPI Generator (https://openapi-generator.tech). DO NOT EDIT.
"""

import unittest

from openfga_sdk.client.models.tuple import ClientTuple
from openfga_sdk.client.models.write_request import ClientWriteRequest


class TestClientWriteRequest(unittest.TestCase):
    """Test for ClientWriteRequest"""

    def test_client_write_request_init_with_no_params(self):
        """Test ClientWriteRequest initialization with no parameters"""
        request = ClientWriteRequest()
        self.assertIsNone(request.writes)
        self.assertIsNone(request.deletes)
        self.assertIsNone(request.on_duplicate)
        self.assertIsNone(request.on_missing)

    def test_client_write_request_init_with_writes(self):
        """Test ClientWriteRequest initialization with writes"""
        writes = [ClientTuple(user="user:alice", relation="viewer", object="doc:1")]
        request = ClientWriteRequest(writes=writes)
        self.assertEqual(request.writes, writes)
        self.assertIsNone(request.deletes)
        self.assertIsNone(request.on_duplicate)
        self.assertIsNone(request.on_missing)

    def test_client_write_request_init_with_deletes(self):
        """Test ClientWriteRequest initialization with deletes"""
        deletes = [ClientTuple(user="user:bob", relation="editor", object="doc:2")]
        request = ClientWriteRequest(deletes=deletes)
        self.assertIsNone(request.writes)
        self.assertEqual(request.deletes, deletes)
        self.assertIsNone(request.on_duplicate)
        self.assertIsNone(request.on_missing)

    def test_client_write_request_init_with_on_duplicate(self):
        """Test ClientWriteRequest initialization with on_duplicate"""
        request = ClientWriteRequest(on_duplicate="ignore")
        self.assertIsNone(request.writes)
        self.assertIsNone(request.deletes)
        self.assertEqual(request.on_duplicate, "ignore")
        self.assertIsNone(request.on_missing)

    def test_client_write_request_init_with_on_missing(self):
        """Test ClientWriteRequest initialization with on_missing"""
        request = ClientWriteRequest(on_missing="ignore")
        self.assertIsNone(request.writes)
        self.assertIsNone(request.deletes)
        self.assertIsNone(request.on_duplicate)
        self.assertEqual(request.on_missing, "ignore")

    def test_client_write_request_init_with_all_params(self):
        """Test ClientWriteRequest initialization with all parameters"""
        writes = [ClientTuple(user="user:alice", relation="viewer", object="doc:1")]
        deletes = [ClientTuple(user="user:bob", relation="editor", object="doc:2")]
        request = ClientWriteRequest(
            writes=writes, deletes=deletes, on_duplicate="error", on_missing="error"
        )
        self.assertEqual(request.writes, writes)
        self.assertEqual(request.deletes, deletes)
        self.assertEqual(request.on_duplicate, "error")
        self.assertEqual(request.on_missing, "error")

    def test_writes_setter(self):
        """Test writes setter"""
        request = ClientWriteRequest()
        writes = [ClientTuple(user="user:charlie", relation="owner", object="doc:3")]
        request.writes = writes
        self.assertEqual(request.writes, writes)

    def test_writes_setter_none(self):
        """Test writes setter with None"""
        writes = [ClientTuple(user="user:alice", relation="viewer", object="doc:1")]
        request = ClientWriteRequest(writes=writes)
        request.writes = None
        self.assertIsNone(request.writes)

    def test_deletes_setter(self):
        """Test deletes setter"""
        request = ClientWriteRequest()
        deletes = [ClientTuple(user="user:dave", relation="viewer", object="doc:4")]
        request.deletes = deletes
        self.assertEqual(request.deletes, deletes)

    def test_deletes_setter_none(self):
        """Test deletes setter with None"""
        deletes = [ClientTuple(user="user:bob", relation="editor", object="doc:2")]
        request = ClientWriteRequest(deletes=deletes)
        request.deletes = None
        self.assertIsNone(request.deletes)

    def test_on_duplicate_setter(self):
        """Test on_duplicate setter"""
        request = ClientWriteRequest()
        request.on_duplicate = "ignore"
        self.assertEqual(request.on_duplicate, "ignore")

    def test_on_duplicate_setter_none(self):
        """Test on_duplicate setter with None"""
        request = ClientWriteRequest(on_duplicate="error")
        request.on_duplicate = None
        self.assertIsNone(request.on_duplicate)

    def test_on_missing_setter(self):
        """Test on_missing setter"""
        request = ClientWriteRequest()
        request.on_missing = "ignore"
        self.assertEqual(request.on_missing, "ignore")

    def test_on_missing_setter_none(self):
        """Test on_missing setter with None"""
        request = ClientWriteRequest(on_missing="error")
        request.on_missing = None
        self.assertIsNone(request.on_missing)

    def test_writes_tuple_keys_with_none_writes(self):
        """Test writes_tuple_keys property with None writes"""
        request = ClientWriteRequest()
        self.assertIsNone(request.writes_tuple_keys)

    def test_writes_tuple_keys_with_empty_writes(self):
        """Test writes_tuple_keys property with empty writes list"""
        request = ClientWriteRequest(writes=[])
        result = request.writes_tuple_keys
        self.assertIsNotNone(result)
        self.assertEqual(result.tuple_keys, [])

    def test_writes_tuple_keys_with_writes(self):
        """Test writes_tuple_keys property with writes"""
        writes = [ClientTuple(user="user:alice", relation="viewer", object="doc:1")]
        request = ClientWriteRequest(writes=writes, on_duplicate="error")
        result = request.writes_tuple_keys
        self.assertIsNotNone(result)
        self.assertEqual(len(result.tuple_keys), 1)
        self.assertEqual(result.on_duplicate, "error")

    def test_writes_tuple_keys_with_on_duplicate(self):
        """Test writes_tuple_keys property includes on_duplicate"""
        writes = [
            ClientTuple(user="user:alice", relation="viewer", object="doc:1"),
            ClientTuple(user="user:bob", relation="editor", object="doc:2"),
        ]
        request = ClientWriteRequest(writes=writes, on_duplicate="ignore")
        result = request.writes_tuple_keys
        self.assertIsNotNone(result)
        self.assertEqual(len(result.tuple_keys), 2)
        self.assertEqual(result.on_duplicate, "ignore")

    def test_deletes_tuple_keys_with_none_deletes(self):
        """Test deletes_tuple_keys property with None deletes"""
        request = ClientWriteRequest()
        self.assertIsNone(request.deletes_tuple_keys)

    def test_deletes_tuple_keys_with_empty_deletes(self):
        """Test deletes_tuple_keys property with empty deletes list"""
        request = ClientWriteRequest(deletes=[])
        result = request.deletes_tuple_keys
        self.assertIsNotNone(result)
        self.assertEqual(result.tuple_keys, [])

    def test_deletes_tuple_keys_with_deletes(self):
        """Test deletes_tuple_keys property with deletes"""
        deletes = [ClientTuple(user="user:bob", relation="editor", object="doc:2")]
        request = ClientWriteRequest(deletes=deletes, on_missing="error")
        result = request.deletes_tuple_keys
        self.assertIsNotNone(result)
        self.assertEqual(len(result.tuple_keys), 1)
        self.assertEqual(result.on_missing, "error")

    def test_deletes_tuple_keys_with_on_missing(self):
        """Test deletes_tuple_keys property includes on_missing"""
        deletes = [
            ClientTuple(user="user:charlie", relation="owner", object="doc:3"),
            ClientTuple(user="user:dave", relation="viewer", object="doc:4"),
        ]
        request = ClientWriteRequest(deletes=deletes, on_missing="ignore")
        result = request.deletes_tuple_keys
        self.assertIsNotNone(result)
        self.assertEqual(len(result.tuple_keys), 2)
        self.assertEqual(result.on_missing, "ignore")
